### ISSUE TITLE
Logo / Icon Design For Geosave

### ISSUE THREAD

**Issue by zularizal** [jakdor/geosave#1]
Hi @jakdor , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by jakdor** [comment]
Hello @zularizal, That would be awesome, I'm currently looking for someone to design an icon! Do you have something interesting on your mind?

**Comment by jakdor** [comment]
The idea behind the app is easy saving, sharing and collaborating on location/GPS data. Online part of the app is designed similar to GitHub – users will be able to create public or private repositories with locations and work together with others.

As far as the name goes - GeoSave looks nice.

Here are the current screenshots:
https://goo.gl/QUQ6nX

Note that I’m not sure if this is the final color palette, I'm open for suggestions and PRs.

If you want to compile project for yourself, I will create a guide on how to obtain API keys in the README file.

Thanks for the interest in the project!

**Comment by zularizal** [comment]
Hi @jakdor , this is the logo for your project. This logo is inspired by the pin map logo, soil layer, and leaves.
In the first color variation, I use yellow, blue and dark blue. The yellow color I take from the theme of your application while the blue color has the meaning of water and soil layer.
What do you think? If something wants to be changed, let me know

![bitmap](https://user-images.githubusercontent.com/38547278/46900697-7ec29180-ced0-11e8-9ec6-ac6e0181e960.png)

**Comment by jakdor** [comment]
Hi @zularizal I like it! The first color variation looks great on the black background. You have a green light for making that into a logo and an icon. I appreciate the effort, thanks!

**Comment by zularizal** [comment]
Hi, I have sent a pull request to you. #2 

And also I have uploaded logos (master files) to the drive 

https://drive.google.com/open?id=1GkR-4wtZZavW9jymd-UApHPO5F6xhq4e

**Comment by jakdor** [comment]
I've merged the pr. That's a top notch work right there! I'm looking forward to working with you in the future!

**Comment by zularizal** [comment]
Okay. If you need a design icon for your other project. You can mention me. I will help you.
